### ISSUE TITLE
XML3d.js does not show in iOS9 Safari

### ISSUE THREAD

**Issue by ksons** [xml3d/xml3d.js#147] opened 2015-09-28 06:08 UTC
From mailing list:
"In the latest iOS, iOS9. I could not load any XML3D in Safari for iOS, not even the most basic examples: http://xml3d.github.io/xml3d-examples/examples/assets/assets.html
Sorry, thanks for all."

Need to be confirmed.

**Comment by csvurt** [comment] 2015-09-30 08:59
Confirmed internally. Seems to be a bug in Safari on IOS9 that doesn't properly expose WebGL constants through the ```WebGLRenderingContext``` object. 

https://twitter.com/pjcozzi/status/638390320619761664

The bug ([148449](https://bugs.webkit.org/show_bug.cgi?id=148449)) seems to have been fixed in WebKit but didn't make it into the IOS 9 release of Safari.

We could workaround this issue by changing all uses of ```WebGLRenderingContext.<constant>``` to ```WebGLRenderingContext.prototype.<constant>``` or by using an instance of the context instead.

**Closed** 2015-10-01 08:39 UTC
