### ISSUE TITLE
simple spotlight + shadow example

### ISSUE THREAD

**Issue by telethonic** [xml3d/xml3d.js#166] opened 2016-01-06 14:24 UTC
Hello,

I've been looking all over for this, to no avail :-(

I've tried to whittle down this example:
http://xml3d.github.io/xml3d-examples/examples/spotLight/index.html
to one that just has the surface, the cube, the spotlight and its light + the cube's shadow.

I thought I could just remove the LampShade geometry from the scene, for example, but apparently not.

Does anyone have a basic spotlight + shadow example?

Also, the "as defined here" link on that page goes to an empty wiki page.
And the 5.0 spec for spot lights is missing falloffAngle (= cutoffAngle?), castShadow,
and shadowBias, is there a later spec that includes these?

Many thanks :)

**Comment by ksons** [comment] 2016-01-07 14:39
Hi @telethonic!

Yes, falloffAngle has been renamed to cutoffAngle. I just fixed that in xml3d/xml3d-examples@08edff4b753ba5bcb20b10c411e8da673f4d0d3a.

I couldn't reproduce your issue with the shadows. If I open the console for:
http://xml3d.github.io/xml3d-examples/examples/spotLight/index.html

and remove the Lamp including cables:

    $("#Lamp,#group1").remove();

it results in a very basic spotlight + shadow example for me (tested this in Chrome and Firefox).

If it does not work for you, can you please give details on which system you are running and if there any errors in the console.

Thanks!

**Comment by telethonic** [comment] 2016-01-07 14:45
Thanks for the quick response :-)

In my test I had downloaded the shadow example HTML file, and all dependent files (so the .js files, .css, etc.).

I then removed the LampShape geometry (so the bit between
```
<data id="LampShape"> ...
</data>
```
and the Lamp group.

So I guess that was the wrong approach, but I'm not sure why :(

**Comment by ksons** [comment] 2016-01-07 15:02
Hi,

the LampShape ```<data>``` element defines the data for a latter mesh (in more recent examples, the geometry data is defined in external resources which results in faster loading times and better handling of the HTML file). So if you remove this data, the ```<mesh>``` element points to an empty data block:

   <mesh src="#LampShape" type="triangles"></mesh>

Since the mesh requires at least positions, you should see following error in the console:

    Mesh Error: Mesh does not have 'position' attribute. 

So you should at least remove the mesh as well.

However, even with these errors I get a correct shadow. Could you please try it the way I sketched above? If it works, I would close the issue.

**Comment by telethonic** [comment] 2016-01-07 15:03
See my edit above, fine to close, thanks.

**Closed** 2016-01-07 15:09 UTC
